# Importing the Dataset

In [65]:
import pandas as pd
import numpy as np
import csv
import math
from sklearn.metrics import confusion_matrix

'''The Following Datasets are prepared during the processing part of the datasets in Linear Regression'''

a = input("Enter 1 for Logistic Regression on Human Observed Data, Concatenated Features\nEnter 2 for Logistic Regression on Human Observed Data, Subtracted Features\n\nEnter 3 for Logistic Regression on GSC Data, Concatenated Features\nEnter 4 for Logistic Regression on GSC Data, Subtracted Features\n")
if(a == str(1)):
    data = pd.read_csv("HOD_concat_dataset_logi.csv")
    M = 18
elif(a == str(2)):
    data = pd.read_csv("HOD_sub_dataset_logi.csv")
    M = 9
elif(a == str(3)):
    data = pd.read_csv("GSC_concat_dataset_logi.csv")
    M = 1024
elif(a == str(4)):
    data = pd.read_csv("GSC_sub_dataset_logi.csv")  
    M = 512
    
data.head()

Enter 1 for Logistic Regression on Human Observed Data, Concatenated Features
Enter 2 for Logistic Regression on Human Observed Data, Subtracted Features

Enter 3 for Logistic Regression on GSC Data, Concatenated Features
Enter 4 for Logistic Regression on GSC Data, Subtracted Features
4


f1_x  f2_x  f3_x  f4_x  f5_x  f6_x  f7_x  f8_x  f9_x  f10_x   ...    \
0     0     0     0     0     0     0     0     0     0      0   ...     
1     0     1     1     0     1     0     0     1     0      0   ...     
2     0     0     0     0     0     0     0     0     0      0   ...     
3     0     0     0     0     0     0     0     0     0      0   ...     
4     0     1     0     0     0     0     0     0     0      0   ...     

   f504_x  f505_x  f506_x  f507_x  f508_x  f509_x  f510_x  f511_x  f512_x  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   target  
0       0  
1       0  
2       0  
3       0  
4       1  

[5 rows x 513 columns]

# Partitioning the Dataset

In [71]:
rows = data.shape[0]
cols = data.shape[1]

#Partitioning the Data
TrainPercent = 80
ValPercent = 10
TestPercent = 10

#Training Set
train_X = data.iloc[0:int(math.ceil(data.shape[0]*0.01*TrainPercent)):,0:cols-1]
train_count= int(math.ceil(data.shape[0]*0.01*TrainPercent))
train_Y = data.iloc[0:int(math.ceil(data.shape[0]*0.01*TrainPercent)):,cols-1:cols]
print("Training Data: ",train_X.shape)
print("Training Target: ",train_Y.shape)

#Validation set
val_size = int(math.ceil(data.shape[0]*ValPercent*0.01))
val_end = train_count + val_size
val_X = data.iloc[train_count+1:val_end,0:cols-1]
val_Y = data.iloc[train_count+1:val_end,cols-1:cols]
print("Validation Data: ",val_X.shape)
print("Validation Target: ",val_Y.shape)

#Testing set
test_X = data.iloc[val_end:data.shape[0],0:cols-1]
test_Y = data.iloc[val_end:data.shape[0],cols-1:cols]
print("Testing Data: ",test_X.shape)
print("Testing Target: ",test_Y.shape)

Training Data:  (114450, 512)
Training Target:  (114450, 1)
Validation Data:  (14306, 512)
Validation Target:  (14306, 1)
Testing Data:  (14305, 512)
Testing Target:  (14305, 1)


In [72]:
train_X = np.array(train_X.values)
train_Y = np.array(train_Y.values)

# Defining Methods

In [73]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def cost(theta, X, Y):
    theta = np.matrix(theta)
    X = np.matrix(X)
    Y = np.matrix(Y)
    term1 = np.multiply(-Y, np.log(sigmoid(X * theta.T)))
    term2 = np.multiply((1-Y), np.log(1 - sigmoid(X * theta.T)))
    return np.sum(term1 - term2) / (len(X))

def evaluate_gradient(theta, X, Y):
    theta = np.matrix(theta)
    X = np.matrix(X)
    Y = np.matrix(Y)
    
    parameters =  int(theta.ravel().shape[1])
    grad = np.zeros(parameters)
    
    error = sigmoid(X*theta.T) - Y
    
    for i in range(parameters):
        term = np.multiply(error, X[:,i])
        grad[i] = np.sum(term) / len(X)
        
    return grad

def accuracy(predicted_labels, actual_labels):
    counter = 0.0
    for i in range (0,predicted_labels.shape[0]):
        if(int(np.around(predicted_labels[i], 0)) == actual_labels[i]):
            counter+=1
    accuracy = (float((counter*100))/float(len(predicted_labels)))
    return accuracy


# Training using Gradient Descent Solution

In [95]:
theta_now = np.zeros(M)
theta_now = np.dot(55, theta_now)
lr = 0.01
Acc = []

for epochs in range(500):
    
    delta_theta = evaluate_gradient(theta_now, train_X, train_Y)
    cost1 = cost(theta_now, train_X, train_Y)
    theta_next = theta_now - (lr*delta_theta)
    theta_now = theta_next
    
    z1 = np.dot(theta_next, (np.transpose(train_X)))
    train_out = sigmoid(z1)
    val = accuracy(train_out, train_Y)
    Acc.append(val)
    

print("Updated Weights: \n",theta_now)
print("Final Training Cost: ",cost1)



Updated Weights: 
 [-2.48293126e-02 -1.77772520e-03 -2.18474585e-03 -1.05123983e-02
 -1.18584138e-02 -1.92585005e-04 -1.46151516e-02  9.61806794e-03
  5.91766342e-03 -6.66324489e-05 -1.27005280e-02 -5.70585751e-03
 -2.26281215e-02  1.35035664e-02  6.20653959e-03  1.65989362e-03
 -1.82255355e-02 -2.05525644e-02 -1.19313141e-03 -3.66968918e-03
 -8.96834434e-03 -2.55678742e-03 -1.52559559e-02 -7.77075425e-03
 -2.12679027e-03  1.40266792e-02 -5.22906136e-04  7.03367582e-03
  1.15882609e-02  4.29671558e-04  2.51346784e-03 -7.39426803e-03
  2.60184551e-03  6.60037037e-04  4.37899014e-03 -1.18737352e-02
 -1.58319866e-02 -1.14707954e-02  1.19963337e-02  1.15043998e-02
  7.93528662e-03  4.35257705e-03 -2.07042714e-02  3.70510366e-03
  8.88324529e-03  3.46653739e-03 -6.08404340e-04  1.06790620e-02
  3.76301894e-03 -3.39863557e-03 -2.31736212e-03 -1.40336321e-02
  1.19812690e-02 -1.97449505e-03  8.42488567e-03 -7.91730028e-03
  1.55890534e-02 -3.36949331e-02 -1.49776719e-02 -3.15057933e-02
 -3.13

# Evaluate Validation and Testing Accuracy

In [96]:
print("Training Accuracy: " + str(np.around(max(Acc),5)))
z2 = np.dot(theta_now, (np.transpose(val_X)))
val_out = sigmoid(z2)
val_Y = np.matrix(val_Y)
vald = accuracy(val_out, val_Y)
val_cost = cost(theta_now, val_X, val_Y)
print("Validation Cost: ",val_cost)
print("Validation Accuracy: ",vald)

z3 = np.dot(theta_now, (np.transpose(test_X)))
test_out = sigmoid(z3)
test_Y = np.matrix(test_Y)
test = accuracy(test_out, test_Y)
test_cost = cost(theta_now, test_X, test_Y)
print("Testing Cost: ",test_cost)
print("Testing Accuracy: ",test)

Training Accuracy: 58.23853
Validation Cost:  0.6822456193818929
Validation Accuracy:  58.12945617223543
Testing Cost:  0.6830839364602043
Testing Accuracy:  57.154840964697655


# Compute the Confusion Matrix

In [91]:
confusion_matrix(train_Y,np.around(train_out,0))

array([[33503, 23709],
       [24546, 32692]], dtype=int64)

In [92]:
confusion_matrix(val_Y,np.around(val_out,0))

array([[4154, 3016],
       [3024, 4112]], dtype=int64)

In [93]:
confusion_matrix(test_Y,np.around(test_out,0))

array([[4094, 3055],
       [3094, 4062]], dtype=int64)

In [94]:
'''Calculating the Precision Score, The precision is intuitively the ability of the classifier not to label 
as positive a sample that is negative. &  The recall is intuitively the ability of the classifier to find all the 
positive samples.
The best value is 1 and the worst value is 0 for both.'''

from sklearn.metrics import precision_score, recall_score
print(precision_score(train_Y, train_out.round(), average='binary'))
print(recall_score(train_Y, train_out.round(), average='binary'))

0.579635112852609
0.5711590202313148


In [89]:
print(precision_score(val_Y, val_out.round(), average='binary'))
print(recall_score(val_Y, val_out.round(), average='binary'))

0.5768799102132436
0.5762331838565022


In [90]:
print(precision_score(test_Y, test_out.round(), average='binary')) 
print(recall_score(test_Y, test_out.round(), average='binary'))

0.5707461008852044
0.5676355505869201
